language: go

go:
  - "1.10"

matrix:
  - fast_finish: true

install:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - curl https://glide.sh/get | sh

script:
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - make

after_success:
  - bash tools/codecov
